### ISSUE TITLE
Watermeter data import

### ISSUE THREAD

**Issue by stefanhirt** [patrickvorgers/Home-Assistant-Import-Energy-Data#19]
It would be nice if you could import old watermeter data, too. Quite similar as gas energy the watermeter data is in m³.

**Comment by patrickvorgers** [comment]
Watermeter data or any other datasource works the exact same way and can be easily added. I can add it next week.
Do you have sample data for me?

**Comment by stefanhirt** [comment]
[Water_Historic_Daily.csv](https://github.com/patrickvorgers/Home-Assistant-Import-Energy-Data/files/14336559/Water_Historic_Daily.csv)
Sure, here is my csv including a watermeter replacement in the past.

**Comment by patrickvorgers** [comment]
Perfect, I will work on it next week because this week I am on holiday.
What is the name of the water supplier which provided this csv export, so I can add it to the list?

**Comment by stefanhirt** [comment]
The csv was created by myself out of my manually readings of the watermeter I used to add into an excel file (therefore I had to interpolate some values). Sadly most german suppliers are years behind on automating these things 😅
So it is pure generic. 
Anyway, enjoy your holiday, I really appreciate your work.

**Comment by patrickvorgers** [comment]
@stefanhirt support for a water sensor has been added. Could you verify?

**Comment by stefanhirt** [comment]
@patrickvorgers thanks, works like intended, I successfully imported my old water meter data.
