### ISSUE TITLE
Feature Request: ZTATZ - P1mon

### ISSUE THREAD

**Issue by AJediIAm** [patrickvorgers/Home-Assistant-Import-Energy-Data#20]
I'm using P1mon (https://www.ztatz.nl/) for energy monitoring, but with Home Assistant, it is redundent. This project provides the perfect oppertunity to get rid of p1mon, so I'm going to try to make a script and post progress and questions here. If someone else already has looked into this, please share.

**Comment by patrickvorgers** [comment]
I can have a look if you have a sample export file of the data.

**Comment by AJediIAm** [comment]
[e_historie.db.xlsx](https://github.com/patrickvorgers/Home-Assistant-Import-Energy-Data/files/14472550/e_historie.db.xlsx)
There are several export functions. The provided sample is from settings > in-export > excel export > e_history. 

[06_watermeter.db.xlsx](https://github.com/patrickvorgers/Home-Assistant-Import-Energy-Data/files/14472565/06_watermeter.db.xlsx)
There is also an option to export the water meter data, but it's in a different format. P1mon stores the data per minute, but after a few months, it is compressed to hourly. I included the cutover point in the sample. The provided sample is from settings > in-export > excel export > 02_watermeter.

I'd appreciate any assistance you can provide. It's been a while since I did some coding myself.

**Comment by patrickvorgers** [comment]
I enhanced your PR and update the template so that it can cope with excel sheets. The PR has been merged into main.
Could you verify?

**Comment by AJediIAm** [comment]
I killed my test instance, so I need to set it up again. Importing the energy data is the first thing on my todo list. 

I performed another data prep with your version and everything looks good so far.
