### ISSUE TITLE
Can't process multiple SolarEdge .json files

### ISSUE THREAD

**Issue by mcwieger** [patrickvorgers/Home-Assistant-Import-Energy-Data#22]
I'm trying to use the SolarEdgeDataPrepare.py script on multiple files, but can't figure it out.

What does work:
-  .json files and SolarEdgeDataPrepare.py in same directory
- run `python SolarEdgeDataPrepare.py 2023_01.json` command
- single file is processed

What does not work:
-  .json files and SolarEdgeDataPrepare.py in same directory
- run `python SolarEdgeDataPrepare.py *.json` command
- following message is shown: `SolarEdgePrepareData usage: SolarEdgePrepareData <SolarEdge .json filename (wildcard)>`

What does not work:
- .json files in folder SolarEdge (without any other files there) and SolarEdgeDataPrepare.py in parent folder
- run `python SolarEdgeDataPrepare.py SolarEdge` or `python SolarEdgeDataPrepare.py SolarEdge *.json` 
- following message is shown: `Found files based on: SolarEdge Only .json datafiles are allowed `

What is the correct syntax for multiple .json files?

**Comment by patrickvorgers** [comment]
I did the below test and multiple json files seems to work on my end:
- Copied the ```solaredge.json``` to ```solaredge1.json``` in the ```Sample files``` directory so that I have multiple json files
- Navigated back to the parent directory
- Executed the below command and got the below output
-  The two files are processed correctly

```
python SolarEdgeDataPrepare.py "Sample files\*.json"
SolarEdge Data Prepare

This python script prepares SolarEdge data for import into Home Assistant.
The files will be prepared in the current directory any previous files will be overwritten!

Are you sure you want to continue [Y/N]?: y
Found files based on: Sample files\*.json
Loading data: Sample files\solaredge.json
Loading data: Sample files\solaredge1.json
Preparing data
Creating file: elec_solar_high_resolution.csv
Done
```

- What kind of OS are you running on?
  - I have tested on Windows.
- What is the python version?
  - ```python --version```

**Comment by mcwieger** [comment]
The variant with a slash I did not try yet:

`python SolarEdgeDataPrepare.py SolarEdge/*.json`

This is the output:
```
SolarEdge Data Prepare                                                           
                                                                                 
This python script prepares SolarEdge data for import into Home Assistant.       
The files will be prepared in the current directory any previous files will be overwritten!                                                                       
                                                                                 
SolarEdgePrepareData usage:                                                      
SolarEdgePrepareData <SolarEdge .json filename (wildcard)>
```

So this one also doesn't work.

I'm using Python in a docker container (Linux), version 3.12.2.

These are the input files:
[2023_02.json](https://github.com/patrickvorgers/Home-Assistant-Import-Energy-Data/files/14584769/2023_02.json)
[2023_01.json](https://github.com/patrickvorgers/Home-Assistant-Import-Energy-Data/files/14584770/2023_01.json)

Had to make some changes to the files already (remove "" from the values, otherwise they were seen as strings instead of number and removed one header from the file to make it similar to the sample input file).

**Comment by patrickvorgers** [comment]
I tested on my end on a Linux Ubuntu container and see the error you are getting. You have to enclose the *.json in quotes to make it work.

Use ```python SolarEdgeDataPrepare.py "*.json"``` instead of ```python SolarEdgeDataPrepare.py *.json```

Can you provide me with the original files without any changes? I can have a look whether I can support it out-of-th-box without any alterations.

**Comment by mcwieger** [comment]
That's it. Linux syntax issue (on my end ;-))

Thanks!

**Comment by mcwieger** [comment]
The original file:

[2023-01.json](https://github.com/patrickvorgers/Home-Assistant-Import-Energy-Data/files/14585406/2023-01.json)

I actually get XML files from SolarEdge, but converting them into JSON (which is a task in itself).

**Comment by patrickvorgers** [comment]
Great!
Looking at the API documentation the API's can return XMl, JSON and CSV formats and defaults to JSON. Are you specifically requesting XML? You have to fill out the accept-header to request a specific format.
Can you request in json format and share that with me so that I have a good sample file?

```
Response Formats
The user can request data in the following formats:
• JSON (application/json)
• XML(application/xml)
• CSV (text/csv).
See specific APIs in the next sections for supported format in each API.
If a specific format is not requested, the data will be retrieved via JSON. If the requested format is invalid, the system will
generate HTTP error "Media not supported".
The API user can request the response format in one of the methods below. The system handles the response format as follows:
• URL format Parameter – …&format=application/json
• Path extension – the name of the API will be followed by the requested format
name ../details.json&…
• HTTP header – based on ‘Accept’ header e.g. Accept application/json
```

**Comment by mcwieger** [comment]
Ran it with .json parameter (rtfm) and it produces the same output as the sample (although not that nicely formatted). The script sees it as a correct .json though, so no need to prettify the code.

[2023-01.json](https://github.com/patrickvorgers/Home-Assistant-Import-Energy-Data/files/14593677/2023-01.json)
