### ISSUE TITLE
Question: Liander data

### ISSUE THREAD

**Issue by fnxpt** [patrickvorgers/Home-Assistant-Import-Energy-Data#32]
I’ve been trying to get the data from Liander, but they send me to my energy provider and my energy provider sends me back to them. Can you share what’s the best way to request this data

**Comment by patrickvorgers** [comment]
It is a bit of hit and miss with Liander and Enexis (NL). Sometimes they give the information and sometimes they don't. What I have heard/experienced; most times they don't. Your energy provider should have the data and be able to share it with you.
