### ISSUE TITLE
historische data uit slimme meterportal

### ISSUE THREAD

**Issue by Kraakie7** [patrickvorgers/Home-Assistant-Import-Energy-Data#53]
Hoi Patrick,

sinds eind 2020 kan ik via slimme meterportal ons energieverbruik inzien.
zou je hiervan ook een script kunnen maken? 

gas data is weergegeven per uur.
elektra is weergegeven per kwartier. leidt dat nog tot beperkingen?

laat maar weten als je meer informatie nodig hebt.

ben benieuwd.
[gasdata_2020_871688540006397097.xlsx](https://github.com/user-attachments/files/16906966/gasdata_2020_871688540006397097.xlsx)
[data_2020_871688540002053522.xlsx](https://github.com/user-attachments/files/16906969/data_2020_871688540002053522.xlsx)

**Comment by patrickvorgers** [comment]
Ik zie het al:
Het bestand kun je aanmaken via `PlusAccount` en dan `Detaildata downloaden`

**Comment by Kraakie7** [comment]
ja klopt.
links is jou document en rechts mijn data, waarbij ook tijdzone is meegenomen

![image](https://github.com/user-attachments/assets/6db41441-52ed-40ef-aa74-b4cd5fdbd906)

**Comment by Kraakie7** [comment]
bovendien registreert slimme meter portal ook de buitentemp.

**Comment by patrickvorgers** [comment]
@Kraakie7, ik heb even snel de ondersteuning toegevoegd. Zou je eens willen kijken of het voor je werkt?

**Comment by Kraakie7** [comment]
het omzetten van de data werkt. krijg nu 4 CSV files. moet ik van alle jaren onder elkaar zetten als ik deze in HA wil zetten?
helaas nu even geen tijd om te importeren. misschien vanavond of morgen. alvast enorm bedankt! ziet er veel belovend uit.

overigens krijg ik voor het omzetten van de csv file van enphase onderstaande fouten
[2096128_aangepast_rapport.csv](https://github.com/user-attachments/files/16910997/2096128_aangepast_rapport.csv)

```
C:\Users\larsk\Home-Assistant-Import-Energy-Data-main\Datasources\Enphase>python EnphaseDataPrepare.py 2096128_aangepast_rapport.csv
Enphase Data Prepare

This python script prepares Enphase data for import into Home Assistant.
The files will be prepared in the current directory any previous files will be overwritten!

Are you sure you want to continue [Y/N]?: y
Found files based on: 2096128_aangepast_rapport.csv
Loading data: 2096128_aangepast_rapport.csv
Preparing data
Traceback (most recent call last):
  File "C:\Users\larsk\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Date/Time'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\larsk\Home-Assistant-Import-Energy-Data-main\Datasources\Enphase\EnphaseDataPrepare.py", line 380, in <module>
    generateImportDataFiles(sys.argv[1])
  File "C:\Users\larsk\Home-Assistant-Import-Energy-Data-main\Datasources\Enphase\EnphaseDataPrepare.py", line 343, in generateImportDataFiles
    dataFrame = prepareData(dataFrame)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\larsk\Home-Assistant-Import-Energy-Data-main\Datasources\Enphase\EnphaseDataPrepare.py", line 173, in prepareData
    dataFrame[inputFileDateColumnName],
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\larsk\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\larsk\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'Date/Time'
```

**Comment by patrickvorgers** [comment]
Alle jaren kun je in 1x importeren. Bij het script moet je ? of * gebruiken om meerdere .xlsx files te selecteren. Het script zal dan alle .xlsx bestanden matchen en dan in een csv bestand zetten.

Ik zal even kijken naar het Enphase bestand.

**Comment by patrickvorgers** [comment]
Voor Enphase moet je zorgen dat de taal op "Engels" staat. In de export staan nu de Nederlandse kolomnamen.

**Comment by Kraakie7** [comment]
dankjewel. voor enphase moest ik uiteindelijk naar account om taal op engels te zetten. enkel aanpassen bij het inloggen werkte blijkbaar niet.

alle bestanden zijn nu aangemaakt. 

ik heb de rest van je gebruikshandleiding gevolgd maar helaas pakt HA niks meer op. 
ik vermoed dat ik onderstaand stukje niet goed begrijp. ben maar een leek ;)

- Change the script and remove/comment out the lines of the sensors that are not needed. They can be found at the top of the script by looking up the lines where /* Change */ has been added in the SQL statement.
- Change the script and update the IDs according to the found IDs in the statistics_meta table. They can be found at the top of the script by looking up the lines where /* Change */ has been added in the SQL statement.
- Determine the correction value based on the unit_of_measurement of the sensor and the used datasource. The unit of measurement of the datasource can be found in the readme of the datasource. The different corrections are described in the script.
- Determine the cutoff_new_meter and cutoff_invalid_value values based on the unit of measurement of the target sensor. The different cutoffs are described in the script.

![image](https://github.com/user-attachments/assets/d51bd3df-b5cb-4357-88cc-8ac136639d74)
![image](https://github.com/user-attachments/assets/f15cffa7-ae2b-4eb9-9f7b-7c985f296bc0)

hopelijk kan je mij helpen.

**Comment by Kraakie7** [comment]
Oh wacht ik heb je sbqpro script niet gebruikt.
Ik kom er nog op terug

**Comment by patrickvorgers** [comment]
Je moet een aantal dingen goed zetten en aanpassen:

- Bij Zonnepanelen moet je van de Envoy alleen de "lifetime energy production" instellen en kun je de "Energy production today" weghalen
- Envoy
  - ID: 15
  - source data: Wh
  - target data: MWh
  - Correction factor: 1000000.0
  - Cutoff new meter: 0.025
  - Cutoff invalid value: 1
- Gas
  - ID: 9
  - source data: m3
  - target data: m3
  - Correction factor: 1.0
  - Cutoff new meter: 25
  - Cutoff invalid value: 1000
- Import tarief 1 / Import tarief 2 / Export tarief 1 / Export tarief 2
  - ID: 2 / 3 / 5 /6
  - source data: kWh
  - target data: kWh
  - Correction factor: 1.0
  - Cutoff new meter: 25
  - Cutoff invalid value: 1000

**Comment by Kraakie7** [comment]
Het werkt! super dankjewel!

Het ging nog niet vlekkeloos. De database raakte steeds corrupt. Waarschijnlijk een klein verschil tussen home-assistant_v2.db extracted van de backup ten opzichte van winSCP. Uiteindelijk home-assistant_v2.db gedownload uit winSCP en na het draaien van het script weer geupload. zoals gezegd ik ben maar een leek, mogelijk heb ik nog andere fouten gemaakt.

onwijs bedankt voor de extra hulp!

**Comment by patrickvorgers** [comment]
Top dat het allemaal gelukt is!
