### ISSUE TITLE
Add support for Enel Distribuzione

### ISSUE THREAD

**Issue by shiner66** [patrickvorgers/Home-Assistant-Import-Energy-Data#61]
Hello,
I'm trying to add support to parse .csv data which can be downloaded from the Enel Distribuzione website (Italian grid authority) and for the love of god, it's so badly formatted that I can't make it work in any way.
Just putting the downloaded data out there if someone wants to take a look at it while I slam my head at their equally bad APIs
[ExportData_settembre.csv](https://github.com/user-attachments/files/17439160/ExportData_settembre.csv)

**Comment by patrickvorgers** [comment]
I had a go at it and made some small changes to the script to handle these type of formats.
Could you try the attached script and check whether it works for you? 

[EnelDistribuzioneDataPrepare.zip](https://github.com/user-attachments/files/17445327/EnelDistribuzioneDataPrepare.zip)

**Comment by shiner66** [comment]
It seems to be working, even tho I didn't import the data in Home Assistant yet.
